[server]
host = "localhost"
port = "8080"
secret = "123456789"
timeZone = "#{SERVER_TIMEZONE}"
limit = 15
prefork = false
strictRouting = false
caseSensitive = true
unescapePath = true

[database]
type = "local"
name = "skyfall.database"
prepareStmt = true
skipDefaultTransaction = true

[middleware]
cache = false
compress = true
logger = true
recover = true
shortener = true
banned = true
traffic = true
