[server]
host = "localhost"
port = "8080"
secret = "123456789"
timeZone = "#{SERVER_TIMEZONE}"
limit = 15
prefork = false
strict-routing = false
case-sensitive = true
unescape-path = true

[database]
type = "local"
name = "skyfall.database"
prepare-stmt = true
skip-default-transaction = true

[middleware]
cache = true
compress = true
logger = true
recover = true
banned = true
